name: python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Install NLTK data
        run: |
          python -m nltk.downloader stopwords
          python -m nltk.downloader punkt
          python -m nltk.downloader wordnet

      - name: Run pytest
        run: |
          python -m pytest dev/tests/ -v --cov=dev --cov-report=xml

      - name: Upload coverage to Codecov # Optional but recommended
        uses: codecov/codecov-action@v3
